#!/usr/bin/env bash
# Azure Database for PostgreSQL Flexible Server + Azure Cache for Redis (Basic tier).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/_common.sh"

echo "==> PostgreSQL Flexible Server ${POSTGRES_SERVER_NAME}"
if ! az postgres flexible-server show -g "${RESOURCE_GROUP}" -n "${POSTGRES_SERVER_NAME}" &>/dev/null; then
  az postgres flexible-server create \
    -g "${RESOURCE_GROUP}" \
    -n "${POSTGRES_SERVER_NAME}" \
    -l "${AZURE_LOCATION}" \
    --admin-user "${POSTGRES_ADMIN_USER}" \
    --admin-password "${POSTGRES_ADMIN_PASSWORD}" \
    --sku-name Standard_B1ms \
    --tier Burstable \
    --storage-size 32 \
    --version 15 \
    --public-access "0.0.0.0-255.255.255.255" \
    --yes \
    --output none
else
  echo "    Postgres server exists, skipping create"
fi

echo "==> Database ${POSTGRES_DATABASE}"
az postgres flexible-server db create \
  -g "${RESOURCE_GROUP}" \
  -s "${POSTGRES_SERVER_NAME}" \
  -d "${POSTGRES_DATABASE}" \
  --output none 2>/dev/null || echo "    Database may already exist"

PG_HOST="${POSTGRES_SERVER_NAME}.postgres.database.azure.com"
DATABASE_URL_ENCODED="$(python3 - "${POSTGRES_ADMIN_USER}" "${POSTGRES_ADMIN_PASSWORD}" "${PG_HOST}" "${POSTGRES_DATABASE}" <<'PY'
import sys
from urllib.parse import quote_plus
user, pwd, host, db = sys.argv[1:]
print(f"postgresql://{quote_plus(user)}:{quote_plus(pwd)}@{host}:5432/{db}?sslmode=require")
PY
)"

echo "==> Azure Cache for Redis ${REDIS_NAME}"
if ! az redis show -g "${RESOURCE_GROUP}" -n "${REDIS_NAME}" &>/dev/null; then
  REDIS_SKU="${REDIS_SKU:-Basic}"
  REDIS_VM_SIZE="${REDIS_VM_SIZE:-c0}"
  az redis create \
    -g "${RESOURCE_GROUP}" \
    -n "${REDIS_NAME}" \
    -l "${AZURE_LOCATION}" \
    --sku "${REDIS_SKU}" \
    --vm-size "${REDIS_VM_SIZE}" \
    --enable-non-ssl-port false \
    --output none
else
  echo "    Redis exists, skipping create"
fi

redis_host=""
while [[ -z "${redis_host}" ]]; do
  redis_host="$(az redis show -g "${RESOURCE_GROUP}" -n "${REDIS_NAME}" --query hostName -o tsv || true)"
  if [[ -z "${redis_host}" ]]; then sleep 15; fi
done

PRIMARY_KEY="$(az redis list-keys -g "${RESOURCE_GROUP}" -n "${REDIS_NAME}" --query primaryKey -o tsv)"
REDIS_URL="rediss://:${PRIMARY_KEY}@${redis_host}:6380/0"

echo ""
echo "Postgres hostname: ${PG_HOST}"
echo "DATABASE_URL (store as Container App secret in next step — shown once here):"
echo "${DATABASE_URL_ENCODED}"
echo ""
echo "REDIS_HOST: ${redis_host}"
echo "Redis uses TLS on port 6380; REDIS_URL pattern (password redacted): rediss://:****@${redis_host}:6380/0"

# Persist to a machine-local file next to azure.env for the next scripts (never commit).
STATE_FILE="${DEPLOYMENT_ROOT}/.deployment-state.generated"
cat >"${STATE_FILE}" <<EOF
# Generated by 02-managed-postgres-redis.sh — do not commit
DATABASE_URL=${DATABASE_URL_ENCODED}
REDIS_URL=${REDIS_URL}
EOF
chmod 600 "${STATE_FILE}"
echo ""
echo "Wrote ${STATE_FILE} (restricted permissions)."
